version: 1.2
workflows:
  - name: bulkRNA_workflow
    subclass: WDL
    publish: True
    primaryDescriptorPath: /rnaseq/RNA_preprocessing_pipeline.wdl
    testParameterFiles: 
      - /rnaseq/test_data/inputs_hg38_STAR_fusion.json
    authors:
      - name: xliu
        email: xliu@whitelabgx.com